bedrock_django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('loginpage.urls'), name='loginpage'),
    path('dashpage',include('dashpage.urls'), name='dashpage'),
    path('solicitation/', include('solicitation.urls'), name='solicitation'),
    # path('central-look-up', include('centrallookup.urls'), name='centrallookup'),
    # path('entityadd', include('entityadd.urls'), name='entityadd'),
    # path('empadmin', include('empadmin.urls'), name='empadmin'),
    # path('messages-system/', include('messagessystem.urls'), name='messages'),
]

dashpage/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='dashpage'
urlpatterns = [
    path('',views.index, name='index'),
    path('logout', views.logout_user, name='logout'),
    path('getonlineusers',views.get_online_users, name='get_online_users'),
]

dashpage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth import authenticate, logout, login
from django.contrib.sessions.models import Session
from datetime import datetime
from pytz import timezone
from solicitation.models import Location, Entity, Entitytype, Employee, Contact, Project, ProjectClass, Sourcetype
from django.core.paginator import Paginator


def index(request):
    if request.user.is_authenticated:
        # return HttpResponse()
        username = request.user.username
        user = Employee.objects.get(username=username)
        user.is_logged_in = True
        user.save()
        bhutan_thimpu = datetime.now(timezone('Asia/Thimphu')).strftime('%d/%h/%Y %I:%M %p')
        us_east = datetime.now(timezone('US/Eastern')).strftime('%d/%h/%Y %I:%M %p')
        us_central = datetime.now(timezone('US/Central')).strftime('%d/%h/%Y %I:%M %p')
        us_mountain = datetime.now(timezone('US/Mountain')).strftime('%d/%h/%Y %I:%M %p')
        us_west = datetime.now(timezone('US/Alaska')).strftime('%d/%h/%Y %I:%M %p')
        india = datetime.now(timezone('Asia/Kolkata')).strftime('%d/%h/%Y %I:%M %p')
        canada_british_columbia = datetime.now(timezone('Canada/Pacific')).strftime('%d/%h/%Y %I:%M %p')
        canada_nova_scotia = datetime.now(timezone('Canada/Eastern')).strftime('%d/%h/%Y %I:%M %p')
        uk_london = datetime.now(timezone('Europe/London')).strftime('%d/%h/%Y %I:%M %p')
        phillipines = datetime.now(timezone('Asia/Manila')).strftime('%d/%h/%Y %I:%M %p')
        context = {
            'us_east': us_east,
            'us_central': us_central,
            'bhutan_thimpu': bhutan_thimpu,
            'india': india,
            'canada_british_columbia': canada_british_columbia,
            'canada_nova_scotia': canada_nova_scotia,
            'us_mountain': us_mountain,
            'us_west': us_west,
            'uk_london': uk_london,
            'phillipines': phillipines,
            'username': username,
        }
        return render(request, 'dashpage/dashpage.html', context)
    else:
        return redirect('loginpage:index')


def logout_user(request):
    user = Employee.objects.get(username=request.user.username)
    user.is_logged_in = False
    user.save()
    logout(request)
    return redirect('/')


def get_online_users(request):
    users = Employee.objects.values('username', 'last_login', 'current_login', 'is_logged_in').order_by('username')
    now_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    online_users = []
    updateuserlogin(request.user.username)
    for user in users:
        is_logged_in = user['is_logged_in']
        if is_logged_in:
            current_login = user['current_login'].strftime('%Y-%m-%d %H:%M:%S')
            duration = datetime.strptime(now_time, '%Y-%m-%d %H:%M:%S') - datetime.strptime(current_login,
                                                                                            '%Y-%m-%d %H:%M:%S')
            if duration.days == 0:
                # return HttpResponse(duration.seconds)
                if duration.seconds < 7:
                    userduration = user['current_login'] - user['last_login']
                    user['duration'] = str(userduration).split(".")[0]
                    online_users.append(user)
    return render(request, 'dashpage/components/online_users.html', {'online_users': online_users})


def updateuserlogin(username):
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S.000000')
    user = Employee.objects.get(username=username)
    user.current_login = now
    user.save()

dashpage/templates/dashpage/components/importjs.html
{% load static %}

<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<script src="{% static 'dist/js/pages/dashboard.js' %}"></script>
<!-- JQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

dashpage/templates/dashpage/components/importstyles.html
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
<link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.css' %}">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

dashpage/templates/dashpage/components/navbar.html
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link">Home</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <form class="form-inline my-2 my-lg-0" action="{% url 'dashpage:logout' %}">
          <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">logout</button>
        </form>
      </li>
    </ul>
  </nav>

dashpage/templates/dashpage/components/online_users.html
<!-- {% for user in online_users %}
<tr>
	<td>{{user.username}}</td>
	<td>{{user.duration}}</td>
</tr> 
{% endfor %} -->

{% for user in online_users %}
    {% if forloop.first %}
        <tr>
    {% endif %}
    <td>
        {{ user.username }} &nbsp&nbsp&nbsp&nbsp	{{ user.duration }}
    </td>
    {% if forloop.counter|divisibleby:"3" %}
        </tr>
    	{% if not forloop.last %}
    	<tr>
    	{% endif %}
    {% endif %}
    {% if forloop.last %}
         </tr>
    {% endif %}
{% endfor %}