bedrock_django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('loginpage.urls'), name='loginpage'),
    path('dashpage',include('dashpage.urls'), name='dashpage'),
    path('solicitation/', include('solicitation.urls'), name='solicitation'),
    # path('central-look-up', include('centrallookup.urls'), name='centrallookup'),
    # path('entityadd', include('entityadd.urls'), name='entityadd'),
    # path('empadmin', include('empadmin.urls'), name='empadmin'),
    # path('messages-system/', include('messagessystem.urls'), name='messages'),
]

dashpage/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='dashpage'
urlpatterns = [
    path('',views.index, name='index'),
    path('logout', views.logout_user, name='logout'),
    path('getonlineusers',views.get_online_users, name='get_online_users'),
]

solicitation/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='solicitation'
urlpatterns = [
    path('',views.index, name='index'),
    path('projectowneradd',views.projectowneradd, name='projectoweneradd'),
    path('projectengineeradd', views.projectengineeradd, name='projectengineeradd'),
 	path('plankeeperadd', views.plankeeperadd, name='plankeeperadd'),
 	path('addsolicitationcontact', views.addsolicitationcontact, name='addsolicitationcontact'),
 	path('manageradd', views.manageradd, name='manageradd'),
 	path('storesolicdata', views.storesolicdata, name='storesolicdata'),

 	path('edit',views.solicitationlist, name='solicitationlist'),
 	path('edit/<int:pk>/', views.editsolicitation, name='editsolicitation'),
 	# path('<int:notenum>', views.viewnotes, name='viewnotes'),
]

solicitation/forms.py
from django import forms
from .models import Project, ProjectTermContract

class TermContractForm(forms.ModelForm):
	class Meta:
		model = ProjectTermContract
		fields = [
		'id',
		'current_start',
		'current_stop',
		'orig_start',
		'orig_stop',
		'contract_term',
		'ext_count',
		'ext_length',
		'status',
		]
class ProjectForm(forms.ModelForm):
	# required_source_url = forms.CharField(max_length=150)
	# name = ownerprjname
	class Meta:
		model = Project
		fields = [
		'source',
		'country',
		'stateprov',
		'county',
		'biddate',
		'bidtime',
		'presolicitation',
		'incomplete',
		'tags',
		'classname',
		'sourcetype',

		'ownerprjname',
		'ownerprjno',
		'location',
		'lowvalue',
		'highvalue',
		'bond',
		'prebiddate',
		'prebidtime',
		'prebidmandatory',
		'codedid',
		# 'status',

		'scope',
		'no_adr',
		'plans',
		'planprice',
		'outsidelink',
		'notes',
		'reporternotes',

		'owner',
		'ownercontact',

		'engineer',
		'engineercontact',
		
		'plan',
		'plancontact',
		'planphone',
		'planphoneext',
		'planfax',
		'planemail',

		'prime',
		'primecontact',
		'leadby',
		'reportby',
		'updatedby',
		
		'worktype',

		'region',
		'name',

		'adr_request_from_ph',
		'adr_request_from_bt',
		'adr_request_from_ca',
		'tags',
		'updatenotes',
		]

solicitation/views.py
from django.shortcuts import render
from . models import *
from django.core.paginator import Paginator
from dashpage.views import updateuserlogin
from django.http import HttpResponse
from .forms import ProjectForm
from . import otherfunctions
import ast
from .forms import TermContractForm
from django.contrib import messages


numberinpages = 10

def index(request):
	context = {
		'bidtimes':otherfunctions.bidtimes,
		# 'countries':Country.objects.all(),
		# 'states':Stateprov.objects.all(),
		# 'countys':County.objects.all(),
		'projectclasses':ProjectClass.objects.all().order_by('classname'),
		'locations':Location.objects.all().order_by('name'),
		'sources':Sourcetype.objects.all().order_by('name'),
		# 'worktypes':Worktype.objects.all(),
		# 'worktypegroups':Worktypegroup.objects.all(),
		'projectstatus':ProjectStatus.objects.all(),

		'utilityconstructions':otherfunctions.utilityconstructions,
		'BuildingTrades':otherfunctions.BuildingTrades,
		'RoadpavingandBridges':otherfunctions.RoadpavingandBridges,
		'architecturalengineeringconsultings':otherfunctions.architecturalengineeringconsultings,
		'SpecialtyTrades':otherfunctions.SpecialtyTrades,
		'OtherServices':otherfunctions.OtherServices,
		'ItemSaleLeaseTrades':otherfunctions.ItemSaleLeaseTrades,
		'ConstructionMaterials':otherfunctions.ConstructionMaterials,
		'PurchaseRentalLeaseofGoods':otherfunctions.PurchaseRentalLeaseofGoods,
		'EquipmentMachineryVehicles':otherfunctions.EquipmentMachineryVehicles,
	}
	# updateuserlogin(request.user.username)
	return render(request,'solicitation/solic_add.html',context)

def projectowneradd(request):
	areacode = request.GET.get('areacode')
	if areacode is None:
		countries = Country.objects.all()
		states = Stateprov.objects.all()
		entity_types = Entitytype.objects.all().order_by('typename')
		context = {
			'countries':countries,
			'states':states,
			'entity_types':entity_types
		}
		return render(request,'solicitation/entities/projectownerselector.html',context)
	else:
		country = request.GET.get('country')
		state = request.GET.get('state')
		phonenumber = request.GET.get('phonenumber')
		city = request.GET.get('city')
		zipcode = request.GET.get('zipcode')
		entitytype = request.GET.get('entitytype')
		ownertype = request.GET.get('ownertype')

		entities = Entity.objects.all().filter(entitytype=5)
		if country is not None and (len(country)>0):
			entities = entities.filter(country=country)
		if state is not None and (len(state)>0):
			entities = entities.filter(stateprov_id=state)
		if phonenumber is not None and (len(phonenumber)>0):
			entities = entities.filter(phone__contains=phonenumber)
		if city is not None and (len(city)>0):
			entities = entities.filter(city=city)
		if zipcode is not None and (len(zipcode)>0):
			entities = entities.filter(zip=zipcode)
		if entitytype is not None and (len(entitytype)>0):
			entities = entities.filter(entitytype_id=entitytype)

		paginator = Paginator(entities,numberinpages)
		page = request.GET.get('page')
		entity_obj = paginator.get_page(page)

		context = {
			'areacode':areacode,
			'entities':entity_obj,
			'state':state,
			'country':country,
			'phonenumber':phonenumber,
			'zipcode': zipcode,
			'city':city,
			'entitytype':entitytype,
			'ownertype':ownertype,
		}
		return render(request, 'solicitation/entities/projectowneradd.html',context)

def projectengineeradd(request):
	country = request.GET.get('country')
	if country is None:
		countries = Country.objects.all()
		states = Stateprov.objects.all()
		context = {
		'countries':countries,
		'states':states,
		}
		return render(request,'solicitation/entities/projectengineerselector.html',context)
	else:
		# page = 	request.GET['page']
		country = request.GET.get('country')
		state = request.GET.get('state')
		phonenumber = request.GET.get('phonenumber')
		city = request.GET.get('city')
		zipcode = request.GET.get('zipcode')
		entities = Entity.objects.all().filter(entitytype=4)
		if country is not None and (len(country)>0):
			entities = entities.filter(country=country)
		if state is not None and (len(state)>0):
			entities = entities.filter(stateprov_id=state)
		if phonenumber is not None and (len(phonenumber)>0):
			entities = entities.filter(phone__contains=phonenumber)
		if city is not None and (len(city)>0):
			entities = entities.filter(city=city)
		if zipcode is not None and (len(zipcode)>0):
			entities = entities.filter(zip__contains=zipcode)

		paginator = Paginator(entities,numberinpages)
		page = request.GET.get('page')
		entity_obj = paginator.get_page(page)

		context = {
			'entities':entity_obj,
			'country':country,
			'state':state,
			'phonenumber':phonenumber,
			'city':city,
			'zipcode':zipcode,
		}
		return render(request, 'solicitation/entities/projectengineeradd.html',context)

def plankeeperadd(request):
	country = request.GET.get('country')
	if country is None:
		countries = Country.objects.all()
		states = Stateprov.objects.all()
		context = {
		'countries':countries,
		'states':states,
		}
		return render(request,'solicitation/entities/plankeeperselector.html', context)
	else:
		# page = 	request.GET['page']
		country = request.GET.get('country')
		state = request.GET.get('state')
		phonenumber = request.GET.get('phonenumber')
		city = request.GET.get('city')
		zipcode = request.GET.get('zipcode')
		entities = Entity.objects.all().filter(entitytype=3)
		if country is not None and (len(country)>0):
			entities = entities.filter(country=country)
		if state is not None and (len(state)>0):
			entities = entities.filter(stateprov_id=state)
		if phonenumber is not None and (len(phonenumber)>0):
			entities = entities.filter(phone__contains=phonenumber)
		if city is not None and (len(city)>0):
			entities = entities.filter(city=city)
		if zipcode is not None and (len(zipcode)>0):
			entities = entities.filter(zip__contains=zipcode)

		paginator = Paginator(entities,numberinpages)
		page = request.GET.get('page')
		entity_obj = paginator.get_page(page)

		context = {
			'entities':entity_obj,
			'country':country,
			'state':state,
			'phonenumber':phonenumber,
			'city':city,
			'zipcode':zipcode,
		}
		return render(request,'solicitation/entities/plankeeperadd.html',context)

def manageradd(request):
	state= request.GET.get('state')
	if state is None:
		states = Stateprov.objects.all()
		entity_types = Entitytype.objects.all()
		context = {
			'states':states,
			'entity_types':entity_types,
		}
		return render(request,'solicitation/entities/managerselector.html', context)
	else:
		phone = request.GET.get('phone')
		entitytype = request.GET.get('entitytype')
		state = request.GET.get('state')
		entityname = request.GET.get('entityname')
		entities = Entity.objects.all()
		if phone is not None and (len(phone)>0):
			entities = entities.filter(phone__contains=phone)
		if entitytype is not None and (len(entitytype)>0):
			entities = entities.filter(entitytype_id=entitytype)
		if state is not None and (len(state)>0):
			entities = entities.filter(stateprov_id=state)
		if entityname is not None and (len(entityname)>0):
			entities = entities.filter(entityname=entityname)

		paginator = Paginator(entities,numberinpages)
		page = request.GET.get('page')
		entity_obj = paginator.get_page(page)
		context = {
			'entities':entity_obj,
			'entityname':entityname,
			'phone':phone,
			'entitytype':entitytype,
			'state':state,
		}
		return render(request,'solicitation/entities/manageradd.html',context)

def addsolicitationcontact(request):
	solicitor = request.GET['solicotor']
	entity_id = request.GET['entityid']
	contact_id = request.GET['contactid']
	if entity_id is None or entity_id == '':
		return HttpResponse('Please select entity first')
	solicitorname = Entity.objects.get(entity_id=entity_id)
	solicitorname = solicitorname.entityname
	if contact_id is None or contact_id == 'None' or contact_id=='':
		contacts = Contact.objects.all()
		messages.info(request, 'Showing all contacts')
	else:
		contacts = Contact.objects.filter(contact_id=contact_id)
		if len(contacts)==0:
			contacts = Contact.objects.all()
			messages.info(request, 'Contact num: '+contact_id+' not found. Showing all contacts')

	paginator = Paginator(contacts,numberinpages)
	page = request.GET.get('page')
	contacts = paginator.get_page(page)

	context = {
	'solicitorname':solicitorname,
	'solicitor':solicitor,
	'entityid':entity_id,
	'contactid':contact_id,
	'contacts':contacts,
	}
	return render(request,'solicitation/entities/addsolicitorcontact.html',context)

def storesolicdata(request):
	projectrequest = otherfunctions.preparedata(request)
	form = ProjectForm(projectrequest)
	if form.is_valid():
		savedform = form.save()
		otherfunctions.savesetaside(request.POST.getlist('setaside'),savedform.pk)
		otherfunctions.savetermcontract(request,savedform.pk)
		return HttpResponse('project saved')
	else:
		print('form error')
		return HttpResponse(otherfunctions.convertformerror(form.errors))

def solicitationlist(request):
	projects = Project.objects.all()
	paginator = Paginator(projects,numberinpages)
	page = request.GET.get('page')
	projects = paginator.get_page(page)
	messages.info(request, 'Showing '+str(numberinpages)+' results')
	return render(request,'solicitation/solicitationlist.html',{'projects':projects})

def editsolicitation(request,pk):
	if request.method == 'POST':
		request.POST = otherfunctions.preparedata(request)
		form = ProjectForm(instance=Project.objects.get(pk=pk),data=request.POST)
		if form.is_valid():
			savedform = form.save()
			otherfunctions.deletesetaside(pk)
			otherfunctions.savesetaside(request.POST.getlist('setaside'),savedform.pk)
			otherfunctions.edittermcontract(request,savedform.pk)
			return HttpResponse('updated')
		else:
			return HttpResponse(form.errors)
	context = {
		'project':Project.objects.get(pk=pk),
		'countries':Country.objects.all(),
		'states' : Stateprov.objects.all(),
		'countys' : County.objects.all(),

solicitation/templates/solicitation/component/information.html
<table class="table border border-dark">
	<thead class="thead-dark">
		<tr>
			<th colspan="5" style="text-align: center; color: #FF99FF">Information</th>
		</tr>
	</thead>
	<tr>
		<td colspan="3">Owner's Solicictation Name <button type="button" class="btn btn-sm btn-info" onclick="case_corrector('owner_solicitation_name')">Case Corrector</button></td>
		<td colspan="2">Owner's Solicitation/Bid Number</td>
	</tr>
	<tr>
		<td colspan="3"><input type="text" class="form-control" name="ownerprjname" value="{{ project.ownerprjname }}" maxlength="150" id="owner_solicitation_name"></td>
		<td colspan="2"><input type="text" class="form-control" name="ownerprjno"  value="{{ project.ownerprjno }}" maxlength="50"></td>
	</tr>
	<tr>
		<td>Location</td>
		<td>Low Value</td>
		<td></td>
		<td>High Value</td>

		<td>Bond: 
			<input type="radio" name="bond" onclick="change_bond_data(5)" id="5%"><label for="5%"> 5%</label> 
			<input type="radio" name="bond" onclick="change_bond_data(10);" id="10%"><label for="10%"> 10%</label>
		</td>
	</tr>
	<tr>
		<td>
			<select name="location" class="form-control">
				<option value="">--select location--</option>
				{% for location in locations %}
				<option value="{{ location.location_id }}" {% if project.location == location %} selected {% endif %}>{{location.name}}</option>
				{% endfor %}
			</select>
		</td>
		<td><input type="number" class="form-control" name="lowvalue" value="{{ project.lowvalue }}"></td>
		<td><button type="button" class="btn btn-sm btn-outline-primary">=</button></td>
		<td><input type="number" class="form-control" name="highvalue" value="{{ project.highvalue }}"></td>
		<td><input type="text" class="form-control" id="bond_data" name="bond" value="{{ project.bond }}"></td>
	</tr>
	<tr>
		<td colspan="1" style="text-align: center;">Pre-bid Date:</td>
		<td colspan="1"><input type="date" name="prebiddate" id="pre_bid_date" class="form-control" value="{{ project.prebiddate|date:'c' }}"></td>
		<td></td>
		<td colspan="2">
			<label style="float: left; margin-right: 20px;" >Pre-Bid Time</label>
			<select name="prebidtime" id="" class="form-control" style="width: 50%;">
				{% for bidtime in bidtimes %}
					<option value="{{ bidtime }}" {% if project.prebidtime == bidtime %}selected{% endif %}>{{ bidtime }}</option>
			{% endfor %}
			</select>
			
		</td>
	</tr>
	<tr>
		{% load customfilter %}
		<td colspan="1"><label for="mandatory">Mandatory</label><input type="checkbox" name="prebidmandatory" id="mandatory" {% if project.prebidmandatory %} checked {% endif %}></td>
		<td colspan="2"><label for="prequal_required">Prequal required</label><input value="8" type="checkbox" name="formpreqrequired" id="prequal_required" {% if project %} {% if project.tags|bitwise_and:8 %}checked{% endif %}{% endif %}></td>
		<td colspan="2">
			<label for="term_contract">Term Contract </label>
			<input type="checkbox" value="16" name="term_contract" id="term_contract" {% if project %} {% if project.tags|bitwise_and:16 %}checked{% endif %}{% endif %}>
		</td>
	</tr>
	<tbody id="term_contract_data"{% if not project %}style="display: none;"{% endif %}>
		<tr>
			<td>Current Contract Start:</td>
			<td> <input type="date" class="form-control" name="current_start" value="{{ termcontract.current_start|date:'c' }}"> </td>
			<td colspan="2">Current Contract End:</td>
			<td> <input type="date" class="form-control" name="current_stop" value="{{ termcontract.current_stop|date:'c' }}"></td>
		</tr>
		<tr>
			<td>Original Contract Start:</td>
			<td><input type="date" class="form-control" name="orig_start" value="{{ termcontract.orig_start|date:'c' }}"></td>
			<td colspan="2">Original Contract End:</td>
			<td><input type="date" class="form-control" name="orig_stop" value="{{ termcontract.orig_stop|date:'c' }}"></td>
		</tr>
		<tr>
			<td>Contract Term in months</td>
			<td><input type="number" class="form-control" name="contract_term" value="{{ termcontract.contract_term }}"></td>
			<td colspan="2">Number of Extentions in months</td>
			<td><input type="number" class="form-control" name="ext_count" value="{{ termcontract.ext_count }}"></td>
		</tr>
		<tr>
			<td>Lenths of Extentions(months)</td>
			<td><input type="number" class="form-control" name="ext_length" value="{{ termcontract.ext_length }}"></td>
			<td colspan="2">Contract Status</td>
			<td>
				<select name="status" class="form-control">
					<option value=""></option>
					{% for status in projectstatus %}
					<option value="{{ status.pk}}" {% if termcontract.status == status.pk %} selected {% endif %}>{{ status.status }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
	</tbody>
</table>

solicitation/templates/solicitation/component/solicjs.html
<script>
	$(document).ready(function () {
		$("#country_search").change(function () {
			// alert('state_search');
			var val = $(this).val();
			{% for country in countries %}
			if (val == {{country.country_id}}) {
				$("#state_search").html('<option value=""></option>{% for state in states %}{% if country.country_id == state.country_id %}<option value="{{state.stateprov_id}}">{{state.name}}</option>{% endif %}{% endfor %}');
			}
			{% endfor %}
		});
		$("#state_search").change(function () {
			// alert('state_search');
			var val2 = $(this).val();
			{% for state in states %}
			if (val2 == {{state.stateprov_id}}) {
				$("#county_search").html('<option value=""></option>{% for county in countys %}{% if state.stateprov_id == county.stateprov_id %}<option value="{{county.county_id}}">{{county.countyname}}</option>{% endif %}{% endfor %}');
			}
			{% endfor %}
		});
		$("#plankeepersameas").change(function () {
			var val = $(this).val();
			if (val == 'sameasowner') {
				document.getElementById("plankeeperid").value=document.getElementById("ownerid").value;
				document.getElementById("plankeepername").value=document.getElementById("ownername").value;
				document.getElementById("plankeeperaddress").value=document.getElementById("owneraddress").value;
				document.getElementById("plankeeperaddress2").value=document.getElementById("owneraddress2").value;
				document.getElementById("plankeepercity").value=document.getElementById("ownercity").value;
				document.getElementById("plakeeperstate").value=document.getElementById("ownerstate").value;
				document.getElementById("plankeeperzip").value=document.getElementById("ownerzip").value;
				document.getElementById("plankeeperphone").value=document.getElementById("ownerphone").value;
				// document.getElementById("plankeepercontactid").value=document.getElementById("ownercontactid").value;
				
			}
			else if (val == 'sameasengineer'){
				document.getElementById("plankeeperid").value=document.getElementById("engineerid").value;
				document.getElementById("plankeepername").value=document.getElementById("engineername").value;
				document.getElementById("plankeeperaddress").value=document.getElementById("engineeraddress").value;
				document.getElementById("plankeeperaddress2").value=document.getElementById("engineeraddress2").value;
				document.getElementById("plankeepercity").value=document.getElementById("engineercity").value;
				document.getElementById("plakeeperstate").value=document.getElementById("engineerstate").value;
				document.getElementById("plankeeperzip").value=document.getElementById("engineerzip").value;
				document.getElementById("plankeeperphone").value=document.getElementById("engineerphone").value;
				// document.getElementById("plankeepercontactid").value=document.getElementById("engineercontactid").value;
				
			}
			else if (val == 'sameasmanager'){
				document.getElementById("plankeeperid").value=document.getElementById("managerid").value;
				document.getElementById("plankeepername").value=document.getElementById("managername").value;
				document.getElementById("plankeeperaddress").value=document.getElementById("manageraddress").value;
				document.getElementById("plankeeperaddress2").value=document.getElementById("manageraddress2").value;
				document.getElementById("plankeepercity").value=document.getElementById("managercity").value;
				document.getElementById("plakeeperstate").value=document.getElementById("managerstate").value;
				document.getElementById("plankeeperzip").value=document.getElementById("managerzip").value;
				document.getElementById("plankeeperphone").value=document.getElementById("managerphone").value;	
			}
		});
		$('#plankeepercontactsameas').change(function(){
			var val = $(this).val();
			if (val == 'sameasowner'){
				document.getElementById("plankeepercontactid").value=document.getElementById("ownercontactid").value;
				document.getElementById("plankeepercontactname").value=document.getElementById("ownercontactname").value;
				document.getElementById("plankeepercontacttype").value=document.getElementById("ownercontacttype").value;
				document.getElementById("plankeepercontactphone").value=document.getElementById("ownercontactphone").value;
				document.getElementById("plankeepercontactext").value=document.getElementById("ownercontactphoneext").value;
				document.getElementById("plankeepercontactfax").value=document.getElementById("ownercontactfax").value;
				document.getElementById("plankeepercontactemail").value=document.getElementById("ownercontactemail").value;
			}
			else if (val == 'sameasengineer'){
				document.getElementById("plankeepercontactid").value=document.getElementById("engineercontactid").value;
				document.getElementById("plankeepercontactname").value=document.getElementById("engineercontactname").value;
				document.getElementById("plankeepercontacttype").value=document.getElementById("engineercontacttype").value;
				document.getElementById("plankeepercontactphone").value=document.getElementById("engineercontactphone").value;
				document.getElementById("plankeepercontactext").value=document.getElementById("engineercontactphoneext").value;
				document.getElementById("plankeepercontactfax").value=document.getElementById("engineercontactfax").value;
				document.getElementById("plankeepercontactemail").value=document.getElementById("engineercontactemail").value;

			}
			else if(val == 'sameasmanager'){
				document.getElementById("plankeepercontactid").value=document.getElementById("managercontactid").value;
				document.getElementById("plankeepercontactname").value=document.getElementById("managercontactname").value;
				document.getElementById("plankeepercontacttype").value=document.getElementById("managercontacttype").value;
				document.getElementById("plankeepercontactphone").value=document.getElementById("managercontactphone").value;
				document.getElementById("plankeepercontactext").value=document.getElementById("managercontactphoneext").value;
				document.getElementById("plankeepercontactfax").value=document.getElementById("managercontactfax").value;
				document.getElementById("plankeepercontactemail").value=document.getElementById("managercontactemail").value;

			}
		})
		
		// $('#term_contract_data').css('display','none');
		$("#term_contract").change(function () {
			if($(this).prop('checked')){
				$('#term_contract_data').show();
			}
			else{
				$('#term_contract_data').hide();
			}
		});
		$("#pre_bid_date").change(function(){
			var reqbid_date = document.getElementById('required_bid_date').value;
			var prebid = $(this).val();
			if (reqbid_date<prebid) {
				alert('prebid cannot be more than bid date');
				document.getElementById('pre_bid_date').valueAsDate = null;
			}
		});
		$('#fed_funding').click(function(){
			if($(this).prop('checked') == true){
				document.getElementById('notes_notes').value += 'This solicitation has some or all federal funding, additional requirements may apply.'
			}
			else{
				textarea = document.getElementById('notes_notes')
				textarea.value = textarea.value.replace("This solicitation has some or all federal funding, additional requirements may apply.","");
			}
		})
		$('#prev_wage').click(function(){
			if($(this).prop('checked') == true){
				document.getElementById('notes_notes').value += 'This project has a "prevailing wage" requirement.'
			}
			else{
				textarea = document.getElementById('notes_notes')
				textarea.value = textarea.value.replace('This project has a "prevailing wage" requirement.',"");
			}
		})
	});
function change_bond_data(x){
	var str = x+"% bond";
	document.getElementById('bond_data').value = str;
}
function clearworktypes(){
	worktypes = document.getElementsByName('worktype')
	// worktypes.checked = false
	for (var i = 0; i < worktypes.length; i++) {
		worktypes[i].checked = False;
    }
}
function case_corrector(input_name) {
	var str = document.getElementById(input_name).value;
	str = str.toLowerCase();
	str = str.split(' ');
	for (var i = 0; i < str.length; i++) {
		str[i] = str[i].charAt(0).toUpperCase() + str[i].slice(1); 
	}
	str = str.join(' ');
	document.getElementById(input_name).value = str;
}
function clear_notes() {
	document.getElementById('notes_notes').value='';
	document.getElementById('fed_funding').checked = false;
	document.getElementById('prev_wage').checked = false;
}
function openownerwindow(){
	window.open ("{% url 'solicitation:projectoweneradd' %}?page=1", "OpenerTest");
}
function openengineerwindow(){
	window.open ("{% url 'solicitation:projectengineeradd' %}?page=1", "OpenerTest");
}
function openplankeeperwindow(){
	window.open("{% url 'solicitation:plankeeperadd' %}","OpenerTest");
}
function openmanagerwindow(){
	window.open("{% url 'solicitation:manageradd' %}","OpenerTest");
}
function solicitationcontact(name){
	var contactid = name+'contactid';
	contactid = document.getElementById(contactid).value;
	var entityid = name+'id';
	entityid = document.getElementById(entityid).value;
	x = 'addsolicitationcontact?solicotor='+name+'&contactid='+contactid+'&entityid='+entityid;
	window.open(x,'OpenerTest');
}
function addfield(){
	number_of_link_fields += 1;
	var input = '<input type="text" style="width:92%;float:left;margin-top:10px;" class="form-control" name="outsidelink" id="linkfield'+number_of_link_fields+'" ><button style="margin:10px 0px 0px 10px;" class="btn btn-primary" id ="buttonlinkfield'+number_of_link_fields+'" onclick=deletefield('+number_of_link_fields+')>Delete</button>';
	// var button = '';
	$('#addfield').append(input);
	// $('#addfield').append(button);
}
function deletefield(x){
	var a = '#linkfield'+x;
	$(a).remove();
	var a = '#buttonlinkfield'+String(x);
	$(a).remove();
	number_of_link_fields -= 1;
}
</script>