bedrock_django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('loginpage.urls'), name='loginpage'),
    path('dashpage',include('dashpage.urls'), name='dashpage'),
    path('solicitation/', include('solicitation.urls'), name='solicitation'),
    # path('central-look-up', include('centrallookup.urls'), name='centrallookup'),
    # path('entityadd', include('entityadd.urls'), name='entityadd'),
    # path('empadmin', include('empadmin.urls'), name='empadmin'),
    # path('messages-system/', include('messagessystem.urls'), name='messages'),
]

dashpage/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='dashpage'
urlpatterns = [
    path('',views.index, name='index'),
    path('logout', views.logout_user, name='logout'),
    path('getonlineusers',views.get_online_users, name='get_online_users'),
]

solicitation/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='solicitation'
urlpatterns = [
    path('',views.index, name='index'),
    path('projectowneradd',views.projectowneradd, name='projectoweneradd'),
    path('projectengineeradd', views.projectengineeradd, name='projectengineeradd'),
 	path('plankeeperadd', views.plankeeperadd, name='plankeeperadd'),
 	path('addsolicitationcontact', views.addsolicitationcontact, name='addsolicitationcontact'),
 	path('manageradd', views.manageradd, name='manageradd'),
 	path('storesolicdata', views.storesolicdata, name='storesolicdata'),

 	path('edit',views.solicitationlist, name='solicitationlist'),
 	path('edit/<int:pk>/', views.editsolicitation, name='editsolicitation'),
 	# path('<int:notenum>', views.viewnotes, name='viewnotes'),
]

solicitation/forms.py
from django import forms
from .models import Project, ProjectTermContract

class TermContractForm(forms.ModelForm):
	class Meta:
		model = ProjectTermContract
		fields = [
		'id',
		'current_start',
		'current_stop',
		'orig_start',
		'orig_stop',
		'contract_term',
		'ext_count',
		'ext_length',
		'status',
		]
class ProjectForm(forms.ModelForm):
	# required_source_url = forms.CharField(max_length=150)
	# name = ownerprjname
	class Meta:
		model = Project
		fields = [
		'source',
		'country',
		'stateprov',
		'county',
		'biddate',
		'bidtime',
		'presolicitation',
		'incomplete',
		'tags',
		'classname',
		'sourcetype',

		'ownerprjname',
		'ownerprjno',
		'location',
		'lowvalue',
		'highvalue',
		'bond',
		'prebiddate',
		'prebidtime',
		'prebidmandatory',
		'codedid',
		# 'status',

		'scope',
		'no_adr',
		'plans',
		'planprice',
		'outsidelink',
		'notes',
		'reporternotes',

		'owner',
		'ownercontact',

		'engineer',
		'engineercontact',
		
		'plan',
		'plancontact',
		'planphone',
		'planphoneext',
		'planfax',
		'planemail',

		'prime',
		'primecontact',
		'leadby',
		'reportby',
		'updatedby',
		
		'worktype',

		'region',
		'name',

		'adr_request_from_ph',
		'adr_request_from_bt',
		'adr_request_from_ca',
		'tags',
		'updatenotes',
		]

solicitation/views.py
from django.shortcuts import render
from . models import *
from django.core.paginator import Paginator
from dashpage.views import updateuserlogin
from django.http import HttpResponse
from .forms import ProjectForm
from . import otherfunctions
import ast
from .forms import TermContractForm
from django.contrib import messages


numberinpages = 10

def index(request):
	context = {
		'bidtimes':otherfunctions.bidtimes,
		# 'countries':Country.objects.all(),
		# 'states':Stateprov.objects.all(),
		# 'countys':County.objects.all(),
		'projectclasses':ProjectClass.objects.all().order_by('classname'),
		'locations':Location.objects.all().order_by('name'),
		'sources':Sourcetype.objects.all().order_by('name'),
		# 'worktypes':Worktype.objects.all(),
		# 'worktypegroups':Worktypegroup.objects.all(),
		'projectstatus':ProjectStatus.objects.all(),

		'utilityconstructions':otherfunctions.utilityconstructions,
		'BuildingTrades':otherfunctions.BuildingTrades,
		'RoadpavingandBridges':otherfunctions.RoadpavingandBridges,
		'architecturalengineeringconsultings':otherfunctions.architecturalengineeringconsultings,
		'SpecialtyTrades':otherfunctions.SpecialtyTrades,
		'OtherServices':otherfunctions.OtherServices,
		'ItemSaleLeaseTrades':otherfunctions.ItemSaleLeaseTrades,
		'ConstructionMaterials':otherfunctions.ConstructionMaterials,
		'PurchaseRentalLeaseofGoods':otherfunctions.PurchaseRentalLeaseofGoods,
		'EquipmentMachineryVehicles':otherfunctions.EquipmentMachineryVehicles,
	}
	# updateuserlogin(request.user.username)
	return render(request,'solicitation/solic_add.html',context)

def projectowneradd(request):
	areacode = request.GET.get('areacode')
	if areacode is None:
		countries = Country.objects.all()
		states = Stateprov.objects.all()
		entity_types = Entitytype.objects.all().order_by('typename')
		context = {
			'countries':countries,
			'states':states,
			'entity_types':entity_types
		}
		return render(request,'solicitation/entities/projectownerselector.html',context)
	else:
		country = request.GET.get('country')
		state = request.GET.get('state')
		phonenumber = request.GET.get('phonenumber')
		city = request.GET.get('city')
		zipcode = request.GET.get('zipcode')
		entitytype = request.GET.get('entitytype')
		ownertype = request.GET.get('ownertype')

		entities = Entity.objects.all().filter(entitytype=5)
		if country is not None and (len(country)>0):
			entities = entities.filter(country=country)
		if state is not None and (len(state)>0):
			entities = entities.filter(stateprov_id=state)
		if phonenumber is not None and (len(phonenumber)>0):
			entities = entities.filter(phone__contains=phonenumber)
		if city is not None and (len(city)>0):
			entities = entities.filter(city=city)
		if zipcode is not None and (len(zipcode)>0):
			entities = entities.filter(zip=zipcode)
		if entitytype is not None and (len(entitytype)>0):
			entities = entities.filter(entitytype_id=entitytype)

		paginator = Paginator(entities,numberinpages)
		page = request.GET.get('page')
		entity_obj = paginator.get_page(page)

		context = {
			'areacode':areacode,
			'entities':entity_obj,
			'state':state,
			'country':country,
			'phonenumber':phonenumber,
			'zipcode': zipcode,
			'city':city,
			'entitytype':entitytype,
			'ownertype':ownertype,
		}
		return render(request, 'solicitation/entities/projectowneradd.html',context)

def projectengineeradd(request):
	country = request.GET.get('country')
	if country is None:
		countries = Country.objects.all()
		states = Stateprov.objects.all()
		context = {
		'countries':countries,
		'states':states,
		}
		return render(request,'solicitation/entities/projectengineerselector.html',context)
	else:
		# page = 	request.GET['page']
		country = request.GET.get('country')
		state = request.GET.get('state')
		phonenumber = request.GET.get('phonenumber')
		city = request.GET.get('city')
		zipcode = request.GET.get('zipcode')
		entities = Entity.objects.all().filter(entitytype=4)
		if country is not None and (len(country)>0):
			entities = entities.filter(country=country)
		if state is not None and (len(state)>0):
			entities = entities.filter(stateprov_id=state)
		if phonenumber is not None and (len(phonenumber)>0):
			entities = entities.filter(phone__contains=phonenumber)
		if city is not None and (len(city)>0):
			entities = entities.filter(city=city)
		if zipcode is not None and (len(zipcode)>0):
			entities = entities.filter(zip__contains=zipcode)

		paginator = Paginator(entities,numberinpages)
		page = request.GET.get('page')
		entity_obj = paginator.get_page(page)

		context = {
			'entities':entity_obj,
			'country':country,
			'state':state,
			'phonenumber':phonenumber,
			'city':city,
			'zipcode':zipcode,
		}
		return render(request, 'solicitation/entities/projectengineeradd.html',context)

def plankeeperadd(request):
	country = request.GET.get('country')
	if country is None:
		countries = Country.objects.all()
		states = Stateprov.objects.all()
		context = {
		'countries':countries,
		'states':states,
		}
		return render(request,'solicitation/entities/plankeeperselector.html', context)
	else:
		# page = 	request.GET['page']
		country = request.GET.get('country')
		state = request.GET.get('state')
		phonenumber = request.GET.get('phonenumber')
		city = request.GET.get('city')
		zipcode = request.GET.get('zipcode')
		entities = Entity.objects.all().filter(entitytype=3)
		if country is not None and (len(country)>0):
			entities = entities.filter(country=country)
		if state is not None and (len(state)>0):
			entities = entities.filter(stateprov_id=state)
		if phonenumber is not None and (len(phonenumber)>0):
			entities = entities.filter(phone__contains=phonenumber)
		if city is not None and (len(city)>0):
			entities = entities.filter(city=city)
		if zipcode is not None and (len(zipcode)>0):
			entities = entities.filter(zip__contains=zipcode)

		paginator = Paginator(entities,numberinpages)
		page = request.GET.get('page')
		entity_obj = paginator.get_page(page)

		context = {
			'entities':entity_obj,
			'country':country,
			'state':state,
			'phonenumber':phonenumber,
			'city':city,
			'zipcode':zipcode,
		}
		return render(request,'solicitation/entities/plankeeperadd.html',context)

def manageradd(request):
	state= request.GET.get('state')
	if state is None:
		states = Stateprov.objects.all()
		entity_types = Entitytype.objects.all()
		context = {
			'states':states,
			'entity_types':entity_types,
		}
		return render(request,'solicitation/entities/managerselector.html', context)
	else:
		phone = request.GET.get('phone')
		entitytype = request.GET.get('entitytype')
		state = request.GET.get('state')
		entityname = request.GET.get('entityname')
		entities = Entity.objects.all()
		if phone is not None and (len(phone)>0):
			entities = entities.filter(phone__contains=phone)
		if entitytype is not None and (len(entitytype)>0):
			entities = entities.filter(entitytype_id=entitytype)
		if state is not None and (len(state)>0):
			entities = entities.filter(stateprov_id=state)
		if entityname is not None and (len(entityname)>0):
			entities = entities.filter(entityname=entityname)

		paginator = Paginator(entities,numberinpages)
		page = request.GET.get('page')
		entity_obj = paginator.get_page(page)
		context = {
			'entities':entity_obj,
			'entityname':entityname,
			'phone':phone,
			'entitytype':entitytype,
			'state':state,
		}
		return render(request,'solicitation/entities/manageradd.html',context)

def addsolicitationcontact(request):
	solicitor = request.GET['solicotor']
	entity_id = request.GET['entityid']
	contact_id = request.GET['contactid']
	if entity_id is None or entity_id == '':
		return HttpResponse('Please select entity first')
	solicitorname = Entity.objects.get(entity_id=entity_id)
	solicitorname = solicitorname.entityname
	if contact_id is None or contact_id == 'None' or contact_id=='':
		contacts = Contact.objects.all()
		messages.info(request, 'Showing all contacts')
	else:
		contacts = Contact.objects.filter(contact_id=contact_id)
		if len(contacts)==0:
			contacts = Contact.objects.all()
			messages.info(request, 'Contact num: '+contact_id+' not found. Showing all contacts')

	paginator = Paginator(contacts,numberinpages)
	page = request.GET.get('page')
	contacts = paginator.get_page(page)

	context = {
	'solicitorname':solicitorname,
	'solicitor':solicitor,
	'entityid':entity_id,
	'contactid':contact_id,
	'contacts':contacts,
	}
	return render(request,'solicitation/entities/addsolicitorcontact.html',context)

def storesolicdata(request):
	projectrequest = otherfunctions.preparedata(request)
	form = ProjectForm(projectrequest)
	if form.is_valid():
		savedform = form.save()
		otherfunctions.savesetaside(request.POST.getlist('setaside'),savedform.pk)
		otherfunctions.savetermcontract(request,savedform.pk)
		return HttpResponse('project saved')
	else:
		print('form error')
		return HttpResponse(otherfunctions.convertformerror(form.errors))

def solicitationlist(request):
	projects = Project.objects.all()
	paginator = Paginator(projects,numberinpages)
	page = request.GET.get('page')
	projects = paginator.get_page(page)
	messages.info(request, 'Showing '+str(numberinpages)+' results')
	return render(request,'solicitation/solicitationlist.html',{'projects':projects})

def editsolicitation(request,pk):
	if request.method == 'POST':
		request.POST = otherfunctions.preparedata(request)
		form = ProjectForm(instance=Project.objects.get(pk=pk),data=request.POST)
		if form.is_valid():
			savedform = form.save()
			otherfunctions.deletesetaside(pk)
			otherfunctions.savesetaside(request.POST.getlist('setaside'),savedform.pk)
			otherfunctions.edittermcontract(request,savedform.pk)
			return HttpResponse('updated')
		else:
			return HttpResponse(form.errors)
	context = {
		'project':Project.objects.get(pk=pk),
		'countries':Country.objects.all(),
		'states' : Stateprov.objects.all(),
		'countys' : County.objects.all(),

solicitation/templates/solicitation/solic_add(old).html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Solic Add</title>
	{% include 'bootstrapimport.html' %}
	<script>
		number_of_link_fields = 0;
	</script>
</head>
<body>
	<div class="container">
		<form action="storesolicdata" method="post">
			{% csrf_token %}
			<table class="table border border-secondary">
				<tr class="thead-dark"><th colspan="7" style="text-align: center; color: red;">Required</th></tr>
				<tr>
					<td class="required">Source</td>
					<td colspan="6"><input type="text" class="form-control" name="required_source_url" required></td>
				</tr>
				<tr>
					<td class="required">Country</td>
					<td style="width: 50px;">
						<select name="required_country_name" id="country_search" class="form-control" required>
							<option value="">---select Country-----</option>
							{% for country in countries %}
							<option value="{{ country.country_id }}">{{ country.name }}</option>
							{% endfor %}
						</select>
					</td>
					<td class="required">State</td>
					<td>
						<select name="required_state_name" id="state_search" class="form-control" >
							<option value="">---select state-----</option>

						</select>
					</td>
					<td colspan="2" class="required" >County</td>
					<td>
						<select name="required_county_name" id="county_search" class="form-control" >
							<option value="">---select county-----</option>
						</select>
					</td>
				</tr>
				<tr>
					<td class="required">Bid Date</td>
					<td><input type="date" class="form-control" name="required_bid_date" required></td>
					<td class="required">Bid Time</td>
					<td>
						<select name="required_bid_time" class="form-control" required>
							<option value="">--select time--</option>
							<option value="9:00 AM">9:00 AM</option>
							<option value="10:00 AM">10:00 AM</option>
							<option value="11:00 AM">11:00 AM</option>
							<option value="12:00 PM">12:00 PM</option>
							<option value="1:00 PM">1:00 PM</option>
							<option value="2:00 PM">2:00 PM</option>
							<option value="3:00 PM">3:00 PM</option>
							<option value="4:00 PM">4:00 PM</option>
							<option value="5:00 PM">5:00 PM</option>
						</select>
					</td>
					<td class="required" colspan="2">
						<label for="presol">Presol</label> 
						<input type="checkbox" name="required_presol" id="presol" value="1">
					</td>
					<td class="required">
						<label for="Incomplete_required">Incomplete</label>
						<input type="checkbox" name="required_incomplete" id="Incomplete_required">
					</td>
				</tr>
				<tr>
					<td class="required">
						<input type="radio" name="required_bidtype" id="requiredPrivate" value="private" required>
						<label for="requiredPrivate">Private</label>
						<input type="radio" name="required_bidtype" id="requiredFederal" value="tags[]">
						<label for="requiredFederal">Federal</label>
						<input type="radio" name="required_bidtype" id="requiredNone" value="none" checked>
						<label for="requiredNone">None</label>
					</td>
					<td  class="required">
						<label for="Sub-Contract">Sub-Contract: </label>
						<input type="checkbox" name="tags[]" id="Sub-Contract">
					</td>
					<td class="required">Class</td>
					<td>
						<select name="required_class" class="form-control" required>
							<option value="">--select class--</option>
							{% for projectclass in projectclasses %}
							<option value="{{projectclass.classname_id}}">{{projectclass.classname}}</option>
							{% endfor %}
						</select>
					</td>
					<td class="required">Source</td>
					<td colspan="2">
						<select name="required_source" id="" class="form-control" required>
							<option value="">-- select source --</option>
							{% for source in sources %}
							<option value="{{source.sourcetypeid}}">{{source.name}}</option>
							{% endfor %}
						</select>
					</td>
				</tr>
			</table>
			<table class="table border border-dark">
				<thead class="thead-dark">
					<tr>
						<th colspan="5" style="text-align: center; color: #FF99FF">Information</th>
					</tr>
				</thead>
				<tr>
					<td colspan="3">Owner's Solicictation Name <button type="button" class="btn btn-sm btn-info" onclick="case_corrector('owner_solicitation_name')">Case Corrector</button> </td>
					<td colspan="2">Owner's Solicitation/Bid Number</td>
				</tr>
				<tr>
					<td colspan="3"><input type="text" class="form-control" name="owner_solicitation_name"></td>
					<td colspan="2"><input type="text" class="form-control" name="bid_number"></td>
				</tr>
				<tr>
					<td>Location <!-- <button type="button" class="btn btn-sm btn-info" onclick="case_corrector('owner_location')">Case Corrector</button> --> </td>
					<td>Low Value</td>
					<td></td>
					<td>High Value</td>

					<td>Bond: 
						<input type="radio" name="bond" onclick="change_bond_data(5)" id="5%"><label for="5%">5%</label> 
						<input type="radio" name="bond" onclick="change_bond_data(10);" id="10%"><label for="10%">10%</label>
					</td>
				</tr>
				<tr>	
					<!-- <td><input type="text" class="form-control" name="owner_location"></td> -->
					<td>
						<select name="owner_location" class="form-control">
							<option value="">--select location--</option>
							{% for location in locations %}
							<option value="{{ location.location_id }}">{{location.name}}</option>
							{% endfor %}
						</select>
					</td>
					<td><input type="text" class="form-control" name="low_value"></td>
					<td><button type="button" class="btn btn-sm btn-outline-primary">=</button></td>
					<!-- <td></td> -->
					<td><input type="text" class="form-control" name="high_value"></td>
					<td><input type="text" class="form-control" id="bond_data" name="bond_percentage"></td>
				</tr>
				<tr>
					<td colspan="1" style="text-align: center;">Pre-bid Date:</td>
					<td colspan="1"><input type="date" name="pre_bid_date" id="pre_bid_date" class="form-control"></td>
					<td></td>
					<td colspan="2">
						<label style="float: left; margin-right: 20px;" >Pre-Bid Time</label>
						<select name="pre_bid_time" id="" class="form-control" style="width: 50%;">
							<option value="9:00 AM">9:00 AM</option>
							<option value="10:00 AM">10:00 AM</option>
							<option value="11:00 AM">11:00 AM</option>
							<option value="12:00 PM">12:00 PM</option>
							<option value="1:00 PM">1:00 PM</option>
							<option value="2:00 PM">2:00 PM</option>
							<option value="3:00 PM">3:00 PM</option>
							<option value="4:00 PM">4:00 PM</option>
							<option value="5:00 PM">5:00 PM</option>
						</select>
					</td>
				</tr>
				<tr>
					<td colspan="1"><label for="mandatory">Mandatory</label><input type="checkbox" name="mandatory" id="mandatory"></td>
					<td colspan="2"><label for="prequal_required">Prequal required</label><input type="checkbox" name="prequal_required" id="prequal_required"></td>
					<td colspan="2">
						<label for="term_contract">Term Contract </label>
						<input type="checkbox" name="term_contract" id="term_contract">
					</td>
				</tr>
				<tbody id="term_contract_data">
					<tr>
						<td>Current Contract Start:</td>
						<td> <input type="text" class="form-control" name="currentcontractstatus"> </td>
						<td colspan="2">Current Contract End:</td>
						<td> <input type="text" class="form-control" name="currenctcontractend" > </td>
					</tr>
					<tr>
						<td>Original Contract Start:</td>
						<td><input type="text" class="form-control" name="originalcontractstart"></td>
						<td colspan="2">Original Contract End:</td>
						<td><input type="text" class="form-control" name="originalcontractend"></td>
					</tr>
					<tr>
						<td>Contract Term in months</td>
						<td><input type="text" class="form-control" name="contract_term"></td>
						<td colspan="2">Number of Extentions in months</td>
						<td><input type="text" class="form-control" name="numberofextention"></td>
					</tr>
					<tr>
						<td>Lenths of Extentions(months)</td>
						<td><input type="text" class="form-control" name="lengthofextentions"></td>
						<td colspan="2">Contract Status</td>
						<td>
							<select name="contract_status" class="form-control">
								<option value=""></option>
								{% for status in projectstatus %}
									<option value="{{ status.pk}}">{{ status.status }}</option>
								{% endfor %}
							</select>
						</td>
					</tr>
				</tbody>
			</table>
			{% include 'solicitation/component/setaside.html' %}
			<div class="row border border-secondary">
				<h5 class="col-lg-12" style="text-align: center; background-color: #252525; color: #fff; padding-top: 10px; padding-bottom: 10px;">NOTES</h5>
				<div class="col-lg-6">
					Scope: <button type="button" class="btn btn-sm btn-info" onclick="case_corrector('notes_scope')">Case Corrector</button>
					<textarea class="form-control "rows="8" name="notes_scope"></textarea>
				</div>
				<div class="col-lg-6">
					Plans and Specs <button type="button" class="btn btn-sm btn-info" onclick="case_corrector('notes_plans_specs')">Case Corrector</button> <input type="checkbox" id="noadr" name="no_adr"><label for="noadr">No ADR</label>
					<textarea class="form-control "rows="8" name="notes_plans_specs"></textarea>
					plan price: <input type="number" style="width: 50%;" name="plan_price">
				</div>
				<div class="col-lg-12"><strong>Outside Link:</strong></div>
				<div id="addfield" class="col-lg-12">
					<input type="text" class="form-control" name="linkfield[]">
				</div>
				<div class="col-lg-12">
					<button type="button" class="btn btn-outline-secondary btn-sm" onclick="addfield()">Add Field</button>
				</div>
				<br><br><br>
				<div class="col-lg-6">
					Notes:
					<button type="button" class="btn btn-sm btn-info" onclick="case_corrector('notes_notes')">Case Corrector</button>
					<button type="button" class="btn btn-sm btn-info" onclick="clear_notes()">Clear Notes </button>
					<input type="checkbox" id="fed_funding" name="fed_funding"><label for="fed_funding">Fed funding</label>
					<input type="checkbox" id="prev_wage" name="prev_wage"><label for="prev_wage">Prev Wage</label>
					<textarea class="form-control "rows="8" name="notes_notes" id="notes_notes"></textarea>
				</div>
				<div class="col-lg-6">
					<p>Reporter Notes</p>
					<textarea class="form-control "rows="8" name="reporter_notes"></textarea>
				</div>
			</div>
			<hr>
			<div class="row">
				<div class="col-lg-2">Solicitor</div>
				<div class="col-lg-10">	
					<select name="Solicotor" class="form-control">
						<option value="">Owner</option>
						<option value="">Engineer</option>
						<option value="">Prime Contractor/Construction Manager</option>
					</select>
				</div>
			</div>
			<hr>
			<div class="row">
				<div class="col-lg-6 border border-secondary">
					{% include 'solicitation/component/ownertable.html' %}
				</div>
				<div class="col-lg-6 border border-secondary">
					{% include 'solicitation/component/engineertable.html' %}
				</div>
			</div>
			<div class="row">
				<div class="col-lg-6 border border-secondary">
					{% include 'solicitation/component/planandspecs.html' %}
				</div>
				<div class="col-lg-6 border border-secondary">
					{% include 'solicitation/component/primecontractor.html' %}
				</div>	
			</div>
			<br>
			<br>
			{% include 'solicitation/component/worktypes.html' %}
			<center><input type="submit" value="submit" class="btn btn-success"></center>
			<br>
		</form>
	</div>
	<br>
	
</body>
{% include 'solicitation/component/solicjs.html' %}
</html>

solicitation/templates/solicitation/solic_add.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Solic Add</title>
	{% include 'bootstrapimport.html' %}
	<script>
		number_of_link_fields = 0;
	</script>
</head>
<body>
	<div class="container">
		<form action="storesolicdata" method="post">
			{% csrf_token %}
			{% include 'solicitation/component/required.html' %}
			{% include 'solicitation/component/information.html' %}
			{% include 'solicitation/component/setaside.html' %}
			<div class="row border border-secondary">
				{% include 'solicitation/component/notes.html' %}
			</div>
			<hr>
			<div class="row">
				<div class="col-lg-2">Solicitor</div>
				<div class="col-lg-10">	
					<select name="Solicotor" class="form-control">
						<option value="">Owner</option>
						<option value="">Engineer</option>
						<option value="">Prime Contractor/Construction Manager</option>
					</select>
				</div>
			</div>
			<hr>
			<div class="row">
				{% include 'solicitation/component/ownertable.html' %}
				{% include 'solicitation/component/engineertable.html' %}
			</div>
			<div class="row">
				{% include 'solicitation/component/planandspecs.html' %}
				{% include 'solicitation/component/primecontractor.html' %}
			</div>
			<br>
			<br>
			{% include 'solicitation/component/worktypes.html' %}
			<center><input type="submit" value="submit" class="btn btn-success"></center>
			<br>
		</form>
	</div>
	<br>
	
</body>
{% include 'solicitation/component/solicjs.html' %}
</html>

solicitation/templates/solicitation/solicitationlist.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Solicitation edit</title>
	{% include 'bootstrapimport.html' %}
</head>
<body>
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-info container text-center" role="alert">
				{{ message }}
			</div>
		{% endfor %}
	{% endif %}
	<table class="table container text-center">
		<thead class="thead-dark">
			<tr>
				<th>Project Num</th>
				<th>Owner name</th>
				<th>State</th>
				<th>County</th>
				<th>date</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for project in projects %}
				<tr>
					<td>{{ project.ownerprjname }}</td>
					<td>{{ project.owner.entityname }}</td>
					<td>{{ project.stateprov }}</td>
					<td>{{ project.county }}</td>
					<td>{{ project.dtlead }}</td>
					<td><a href="{% url 'solicitation:editsolicitation' project.pk %}">Edit</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% include 'solicitation/edit-solicitation/solicitation_list_pagination.html' %}
</body>
</html>